# yamllint disable-file
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgByQU2ojYg/m8NAAc+gqNET9M9/b+xNil5LP1pKg/QNnwv8iGwXlkG2mxAVkaxbfjvLaECF29ZWw51mzl4Fte0+0+yaWnh0vf+f1YGYFviR5CeVIQpCSRgtxgIY28Tnd7/jTqRjb/ufS48gplv5P+RpocYxto82vpIE2BlOSi1hWOIXOlgt7SqPqAblLpvCJgbAPr50TJlPGtQV0ewunaO/mfqhn0/cOjETiYAdrupqxVcKBU6G8gyvuFGzC6DbKeQSTyHw+pF336XHthY+7ySl+L+EDa2OA1K+I9F+M59h6gPbIm4rXK/X/1xoREombANvN8du1lGma15cdozxzS9Jn283PNoraxv9L+ft1QtH5ClSbiL/WCsD/KZyO2SpiJveXhuJGEhzwUdlQ+0+H+AvGvVLFK0NhA+cAU17BJhyfIpI/HSmFpHF2DBUQoeAJt+LgIBMhseOb6W2Edep/cVlCn9zdly5l5/m6G57uOqxptE5+WxNobetqeg42LUlgBQBhpFo0bDY28EevJ3sExNRo4Y4PFpTz6X0meqVFAWD4im6j+Lrsw6OU9/4SKpkNxZiq3TV5kf47dyfDJGPxLmq9CKSXZTBahHNExCA80n+rBgHb5jlu8+JOV/AwS0DZrRpA5Nv2K9KoFxjzIsCBtOmHGZzgCI2AHcHfP1tdk0Ez3TQmTn2OyeFcf+5Effq7d2sB7eMGNBfmS35ua8yREhNWkQsvk5YLX961fucZlnxkFeGfJy6
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: cert-manager
    type: Opaque
