apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-tank-franxx
spec:
  storageClassName: media-tank-franxx
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: franxx
    path: /tank/share
  mountOptions:
    # - tcp
    # - intr
    # - hard
    # - noatime
    # - nodiratime
    # - rsize=1048576
    # - wsize=1048576
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-tank-franxx
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-tank-franxx
  resources:
    requests:
      storage: 1Mi