---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: phpldapadmin
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: phpldapadmin
      version: 0.1.4
      sourceRef:
        kind: HelmRepository
        name: cetic-charts
        namespace: gotk-system
      interval: 5m
  values:
    image:
      repository: osixia/phpldapadmin
      tag: 0.9.0
    service:
      type: ClusterIP
    ingress:
      enabled: true
      path: /
      hosts:
        - ldap-admin.56k.jp
      tls:
        - hosts:
            - ldap-admin.56k.jp
    env:
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_TRUST_PROXY_SSL: "true"
      PHPLDAPADMIN_LDAP_HOSTS_FRIENDLY: "true"
      PHPLDAPADMIN_LDAP_HOSTS: |
        - 56k:
            - server:
                - host: openldap
                - tls: true
            - login:
                - bind_id: cn=admin,dc=56k,dc=jp
      PHPLDAPADMIN_SERVER_PATH: "/"
