---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openldap
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: openldap
      version: 1.2.5
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: osixia/openldap
      tag: 1.4.0
    logLevel: debug
    tls:
      enabled: true
      secret: ldap-56k-jp-tls
    service:
      type: LoadBalancer
      externalIPs:
        - 10.0.35.67
    env:
      LDAP_ORGANISATION: "56k"
      LDAP_DOMAIN: "56k.jp"
      LDAP_RFC2307BIS_SCHEMA: "true"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "false"
      LDAP_TLS_CA_CRT_FILENAME: "tls.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_VERIFY_CLIENT: "never"
    persistence:
      enabled: true
  valuesFrom:
    - kind: Secret
      name: "openldap-helm-values"
