apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: plex
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: gotk-system
      interval: 5m
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 1m
    cleanupOnFail: true
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.20.2.3402-0fec14d92
      pullPolicy: IfNotPresent
    timezone: "America/Chicago"
    allowedNetworks:
      - 127.0.0.1
      - 10.0.20.0/24
      - 10.0.30.0/24
      - 10.0.35.0/24
      - 10.233.0.0/18
    advertiseIp: "http://10.0.35.65:32400"
    serviceTCP:
      type: LoadBalancer
      externalIPs:
        - 10.0.35.65
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: plex
    serviceUDP:
      type: LoadBalancer
      externalIPs:
        - 10.0.35.65
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: plex
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts: [watch.56k.jp]
      tls:
      - hosts:
        - watch.56k.jp
    persistence:
      transcode:
        enabled: true
        size: 40Gi
      data:
        enabled: false
      config:
        storageClass: longhorn
        size: 250Gi
        accessMode: ReadWriteOnce
      extraMounts:
      - name: tank-franxx
        claimName: nfs-tank-franxx
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - franxx