apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack-charts
  namespace: gotk-system
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
  timeout: 3m