# yamllint disable-file
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgCCAZOAsXwNEaE0BmxAVQxzHv1NFl4kD56qXsebdAk551xWV8zRJX7CPkQkvujmLlgw1hflhndKL0WI5KQECvsRwldKHqT671HDm8ZUZccaSya3Emm/NwgBNr2LpssqcNDf/jDOcVwVbCFRTYI6RVKIcx0ON0VRpGjOl941fTJN0Gmr2ZWXANJEz73jqlYq9ntxw1WL0VcXqYBAIXodbaybuBLWtZBQwO3zZF+xFG/AESuoEnvjDsQt+sQztIloKBUHG2ixFDCFVhR1/ONTbBx7sMF2RbnD8DEHI/JB0+yd4j36/UvmHQfmGk+nzDB3xxtB58aq+pDbP7PsXFeqKwToipygZxKm+WDQ8NbZs/I6/RSPqEkgg0f5fvJWBDK20dzH5CauwCANeyO6hCHiTWfO5wVmDHBWTl0c+dVDtw0chS8oR5F0K5QuwMLNTEQFYl2+umb+YYz4fKphZ6CMFeCnj/2ysCTZrlrt1hZt3oMjn2GTXW1RNiz9W24vmclZqu29Vp9DTvgblt1PH7vIVqw5PP9U8ta49MU017WzBPkqKdmDhTruao2qPnRIEzCOYIpdG/6c8jG1jOVSQAhUUbPkPl9zPOKz+JLoo+EInimm2zdkeOoRHhYrHgY3wcX8g2cUqixGIMLy3/g1CsAEwTuRHYkqzpECqfWqN81NTaQ7Z6+KFixJQUGhhg+cewc7kGHO2t7IsY2CsFCmE+cnDvBaR/tyDburWlGwFPu8OSrDN6XP4lK7bYzmSAdG6ORdRO7wG1iNpCwgc0wb3FXAOYbrn0KWsO0iE6uG4UOUN4sdwcQ=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
