apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner
  namespace: kube-system
  creationTimestamp: null
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-client-provisioner
      version: 1.2.9
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable-charts
        namespace: gotk-system
      interval: 5m
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 1m
    cleanupOnFail: true
  values:
    nfs:
      server: franxx
      path: /vmstore/kubedata
      mountOptions: