---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 3.4.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  values:
    controller:
      service:
        type: LoadBalancer
        loadBalancerIp: 10.0.35.64
        externalTrafficPolicy: Local
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: kube-system
      extraArgs:
        default-ssl-certificate: "kube-system/56k-jp-tls"
