---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: utility-nfs-data-franxx
spec:
  storageClassName: utility-data-franxx
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: franxx
    path: /tank/data
  mountOptions:
  # - tcp
  # - intr
  # - hard
  # - noatime
  # - nodiratime
  # - rsize=1048576
  # - wsize=1048576
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-franxx
  namespace: utility
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: utility-data-franxx
  resources:
    requests:
      storage: 1Mi
