---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: oauth2-proxy
      version: 3.2.3
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable-charts
        namespace: gotk-system
      interval: 5m
  values:
    image:
      repository: quay.io/pusher/oauth2_proxy
      tag: v6.1.1
    replicaCount: 1
    ingress:
      enabled: true
      hosts:
        - auth.56k.jp
      tls:
        - hosts:
            - auth.56k.jp
    extraArgs:
      provider: oidc
      provider-display-name: "56k"
      oidc-issuer-url: "https://idp.56k.jp/auth/realms/56k"
      login-url: "https://idp.56k.jp/auth/realms/56k/protocol/openid-connect/auth"
      redeem-url: "https://idp.56k.jp/auth/realms/56k/protocol/openid-connect/token"
      validate-url: "https://idp.56k.jp/auth/realms/56k/protocol/openid-connect/userinfo"
      skip-provider-button: true
      email-domain: "*"
      cookie-domain: ".56k.jp"
      whitelist-domain: ".56k.jp"
  valuesFrom:
    - kind: Secret
      name: "oauth2-proxy-helm-values"
