apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBaHiact0/+nKae3ZyADS0Mn9bAFib8S9J99501yQNp5k8ea5KjaFWSwwrVswfz5gWskrIcl/g8KXD3iIoj9OX6w1ewJJ0I0Qmm1R1f3IdkCA1tNN4n5vebQchnyvk/XGtgyqwUWMzxKJkGOgiI09yluyjaPWrCk9YbHMQj/twPhoKzAYUa9aFzQwfkyLPcdCh9BxGUuYAnMepRfYFb8M7686TTsU63+nUHEe+KeTR2s3q6T0kCmSNFNQCJxuv9sSKwpvBvLe8nl9hxR+XBxn/+fDa/kfBU7QB9RTwIxLy0jR3mCT73fQSWCU0OiDEAMTf4HIaj04hwybO1SkqK/dzr6pFm/Oz2ZtgHvaZJidqUSE4pmJRZ1ukqHa1Hyi2EJn6HkvBIHHhmToxbUQd1jYETcPrwZPFjlJieusWKkpYnohlRQ3/nc4ZPtBfFcsGhBwAJdF+w443GYvH3h2YLT+TXXNhFJIOlWILwkj3A9MJfSZoVntZnASxzIABB0PiHE5CqUvU1AIvogrSryPluJlEfQYTXb9P/CdYJ2Y3nJ3gOMD96pydMVUXC7jQiDrfYAty7HBglATWupkDaH0cwSlWZXdsfgjetWT0NjEI1ZbsMy+5E+uKuygTybTgbghHCzDW8+tiE/owWcZrtK5HScijbvMUkKeonKPxM1HUBD8xMp5AvNAZvpQ7vS3xdF32okSGnhMsiZAES
    admin-user: AgAlOI5bwKx4pdfwcQ45an2ex1/6mC4Sjd8SKC3U+7UWlG4dTgU7hYf0KsamGDKWlx3koXScxbCtWvMKRkTHEXdzGOWJdIPZDNomVJoK7ZTVxEBXKKhnZfJLbUuOdvTFSri0Ezry4+9Ld8bgAifa78wyeKDqc/ZWMdJErSE4cJ0pjMMAkHY1dAIgjYirzAt84/BsDtutf18zz+XDzeARVrkNwOeHvu3VzdUwhx1EphLkBhZ3htsuy16t0SCpQnH+YhM2yz7JsL9ucfXO0PnMLX1slQ2gcrM8LxNYDKV5zi4LOdKjAsI5ZIll+4neWsB94p2r57pQIiC4NKKBdn701k4rtCfkjuxvIBMMTxUrp+e6IwkiDuwIaC5h8SgiBjkouuT8jp3XNrxsuwun1LlTxsbl3eLd2QruCTlhvIh07EAFB7Zuf36p1BFpEvkMutCumwIxcnIznX6hTDLyhdplLMbrm+cPNT14cQeBCj/vR5OMrLJASh41FF3kgcmzGNlopvV5aTMkTihJe276UZvewCfjYouleKmOpXNugV3Se1CJlSDr7leRFdH+BT1bCW6WoV9P23/+Tbbf3w7UBe13rvI3VtBriU9HkacfIlfnbFjIKqLhE7S9GcEmjgOR51sAxe/js4GDk3aQJOkCdgBEAx8J7JL4rs0vDLeszvDvZrWLNdsBRM5DHNIXpVc377MIXQvfG+O9RFghtQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-creds
      namespace: monitoring
    type: Opaque

